### ISSUE TITLE
Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?

### ISSUE THREAD

**Issue by chudaozhe** [Jetty53/FloatingWindowAndroid#1]
Hello, I failed to run this demo, the android version I am using is 7.1.1, hint

```
    Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?

  at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)

       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)

       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)

       at com.wheic.floatingedittext.FloatingWindowGFG.onCreate(FloatingWindowGFG.java:117)

```

**Comment by a2505** [comment]
请问这个你解决了吗
